import Head from "next/head";

import { PrismaClient } from "@prisma/client";
import { GetServerSideProps } from "next";
import { useForm } from "react-hook-form";
import { FormValues, Input } from "../components/Input";
import { useState } from "react";

const prisma = new PrismaClient();

export const getServerSideProps: GetServerSideProps = async () => {
  const fetchedMovies = await prisma.movie.findMany();
  return {
    props: {
      fetchedMovies,
    },
  };
};

export default function Home({ fetchedMovies }) {
  const { handleSubmit, control } = useForm<FormValues>();
  const [movies, setMovies] = useState(fetchedMovies);

  const onSubmit = async (values: FormValues) => {
    try {
      const res = await fetch("/api/movies", {
        method: "POST",
        body: JSON.stringify(values),
      });
      if (res.ok) {
        setMovies([...movies, values]);
      }
    } catch (err) {
      throw new Error(err);
    }
  };
  return (
    <div className="bg-gray-600 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        {movies.map((m) => (
          <h2 key={m.id}>
            {m.title} - {m.genre}
          </h2>
        ))}
        <Input name="title" control={control} />
        <Input name="genre" control={control} />
        <button onClick={handleSubmit(onSubmit)}>Submit</button>
      </main>
    </div>
  );
}
